// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPo__I2Izw68LbQWuO8-GcFoUL9PYM57w',
    appId: '1:716559931508:web:4e7bb7fff99c15c0a1d921',
    messagingSenderId: '716559931508',
    projectId: 'shared-todo-c83d0',
    authDomain: 'shared-todo-c83d0.firebaseapp.com',
    storageBucket: 'shared-todo-c83d0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_Ng-zVyD4kflbJ1Cdpm33JakL0mm4N1Q',
    appId: '1:716559931508:android:cbc3a7f142affbb1a1d921',
    messagingSenderId: '716559931508',
    projectId: 'shared-todo-c83d0',
    storageBucket: 'shared-todo-c83d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDngQ7IgkEiBh91_R_SAgTBMQNbqIts3Nw',
    appId: '1:716559931508:ios:aad5e06825562a95a1d921',
    messagingSenderId: '716559931508',
    projectId: 'shared-todo-c83d0',
    storageBucket: 'shared-todo-c83d0.firebasestorage.app',
    androidClientId: '716559931508-mpb7o1d8o57hbinqjo7bhmghj7etq5pk.apps.googleusercontent.com',
    iosClientId: '716559931508-tl7gkhrli5cutde7pcbkee4lbpikcioo.apps.googleusercontent.com',
    iosBundleId: 'com.example.sharedTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDngQ7IgkEiBh91_R_SAgTBMQNbqIts3Nw',
    appId: '1:716559931508:ios:aad5e06825562a95a1d921',
    messagingSenderId: '716559931508',
    projectId: 'shared-todo-c83d0',
    storageBucket: 'shared-todo-c83d0.firebasestorage.app',
    androidClientId: '716559931508-mpb7o1d8o57hbinqjo7bhmghj7etq5pk.apps.googleusercontent.com',
    iosClientId: '716559931508-tl7gkhrli5cutde7pcbkee4lbpikcioo.apps.googleusercontent.com',
    iosBundleId: 'com.example.sharedTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPo__I2Izw68LbQWuO8-GcFoUL9PYM57w',
    appId: '1:716559931508:web:6e7ac7bce4b6d7cfa1d921',
    messagingSenderId: '716559931508',
    projectId: 'shared-todo-c83d0',
    authDomain: 'shared-todo-c83d0.firebaseapp.com',
    storageBucket: 'shared-todo-c83d0.firebasestorage.app',
  );

}